@startuml use_case

skinparam use_case {
    'for actions that are directly connected to the actor
    BackgroundColor<< user action >> YellowGreen
}

left to right direction

actor :User:

(Provide an input expression) as input<<user action>>
(Use the numpad) as numpad
(Use the keyboard) as keyboard
(Press Enter) as enter<<user action>>
(Call the parser) as parser
(Display an error) as error
(Compose the result variable) as calculate
(Store variables) as store
(Calculate an approximation) as calc_approx
(Ask for long approximation) as ask_approx<<user action>>
(Display approximation window) as approx_window
(Set precision) as set_precision<<user action>>

User -> input
User -> enter
User -> ask_approx
User -> set_precision

input ..> numpad : <<extends>>
input ..> keyboard : <<extends>>

input .down.> enter : <<precedes>>
enter ..> parser : <<invokes>>
parser ..> error: <<invokes>>
parser ..> calculate: <<invokes>>
calculate ..> calc_approx: <<precedes>>
calculate ..> store: <<extends>>

enter .down.> ask_approx: <<precedes>>
ask_approx ..> approx_window: <<invokes>>
ask_approx ..> calc_approx: <<invokes>>

ask_approx .down.> set_precision: <<precedes>>
set_precision ..> calc_approx: <<invokes>>

@enduml
