@startuml packages

component Tool

component Algebra

component Operator
Operator ..> Algebra

component Implementation
Implementation ..> Algebra
Implementation ..> Operator #ffaa00
' see Shift
Operator ..> Implementation #ffaa00
' see PosRational
Implementation ..> Tool

component RealTheory
RealTheory ..> Algebra
RealTheory ..> Operator
RealTheory ..> Implementation

component Function
Function ..> RealTheory
Function ..> Tool

@enduml
